config/routes.rb
Rails.application.routes.draw do

  get 'createtask/new'

  get 'createtask/create'

  get 'profile/show'

  get 'profile/edit'

  get 'profile/update'

  get 'mytasks/show'

  get 'mytasks/finish'

  get 'mytasks/unaccept'

  get 'mytasks/info'

  get 'opentasks/index'
  
  get 'opentasks/new'

  get 'opentasks/create'

  get 'opentasks/delete'

  get 'opentasks/show'

  get 'opentasks/accept'

  devise_for :posters
  get 'welcome/index'

  get 'sessions/new'

root 'welcome#index'

end

app/models/poster.rb
class Poster < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :configure_permitted_parameters, if: :devise_controller?

    protected

        def configure_permitted_parameters
            devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:name, :email, :password) }
            devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:name, :email, :password, :current_password, :is_female, :date_of_birth) }
        end
end

app/controllers/createtask_controller.rb
class CreatetaskController < ApplicationController
  def new
  end

  def create
  end
end

app/controllers/mytasks_controller.rb
class MytasksController < ApplicationController
  def show
  end

  def finish
  end

  def unaccept
  end

  def info
  end
end

app/controllers/opentasks_controller.rb
class OpentasksController < ApplicationController

  def new
  end

  def create
  end

  def delete
  end

  def show
  end

  def accept
  end
end

app/controllers/profile_controller.rb
class ProfileController < ApplicationController
  def show
  end

  def edit
  end

  def update
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

	before_action :authenticate_poster!
  def index
  end



end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/createtask_helper.rb
module CreatetaskHelper
end

app/helpers/mytasks_helper.rb
module MytasksHelper
end

app/helpers/opentasks_helper.rb
module OpentasksHelper
end

app/helpers/profile_helper.rb
module ProfileHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/createtask/create.html.erb
<h1>Create and Submit a Task!</h1>
<p>Submit a Task that and wait for a SquidRunner to help out!</p>

<%= form_tag("/search", method: "get") do %>
  <%= label_tag(:q, "Task Category:") %>
  <%= select(:person, :city_id, [['--Select--', 0],['Food', 1], ['Laundry', 2], ['Miscellaneous', 3],['Package', 4] ]) %>
  <br>
  <%= label_tag(:q, "PickUp Location:") %>
  <%= select(:person, :city_id, [['--Select--', 0],['Dorm', 1], ['Frist', 2], ['Nassau', 3],['Off Campus', 4],['N/A', 5] ,['Other', 6]  ]) %>
  <br>
  <%= label_tag(:q, "Delivery Location:") %>
  <%= select(:person, :city_id, [['--Select--', 0],['Dorm', 1], ['Frist', 2], ['Nassau', 3],['Off Campus', 4],['N/A', 5],['Other', 6]]) %>
  <br>
  <%= label_tag(:q, "Task Title:") %>
  <%= text_field_tag(:q) %>
  <br>
  <%= label_tag(:q, "Paying ($):") %>
  <%= text_field_tag(:q) %>
  <br>
  <%= label_tag(:text, "Task Description:") %>
  <br>
  <%= text_area_tag(:text, "", :size => "50x5") %>
  <br>
  <%= submit_tag("Submit Task") %>
<% end %>

app/views/createtask/new.html.erb
<h1>Createtask#new</h1>
<p>Find me in app/views/createtask/new.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Squid</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
      </script>
    <![endif]-->
</head>
<body>
  <header class="navbar navbar-fixed-top navbar-inverse">
    <div class="container">
      <%= link_to "SquidRunner", '#', id: "logo" %>
      <% if poster_signed_in? %>
      <nav>
        <ul class="nav navbar-nav navbar-right">
          <li><%= link_to "Home",   controller: '/welcome' %></li>
          <li><%= link_to "CreateTask", controller: '/createtask', action:"create" %></li>
          <li><%= link_to "OpenTasks", controller: '/opentasks', action:"show" %></li>
          <li><%= link_to "MyTasks",   controller: '/mytasks', action:"show" %></li>
          <li><%= link_to "MyProfile",   controller: '/profile', action:"show" %></li>
          <li><%= link_to 'Edit Profile',edit_poster_registration_path(@poster) %></li>
          <li><%= link_to "Dummy",   '#' %></li>
          <li><%= link_to('Logout', destroy_poster_session_path, :method => :delete) %></li>
        </ul>
      </nav>
      <% end %>
    </div>


  </header>
  <div class="container">
    <% if !poster_signed_in? %>
      <%= image_tag("squidrunner.png", :alt => "shit broke") %>
    <% end %>

    <%= yield %>
       <p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>
     </div>

</body>
<footer class="footer">
  <small>
    The <a href="http://www.princeton.edu/~yc4">SquidMinion</a>
    by <a href="http://www.eddible.net/">Alex, Eddie and Zhengyang </a>
  </small>
  <nav>
    <ul>
      <li><%= link_to "Dummy",   '#' %></li>
      <li><%= link_to "Dummy", '#' %></li>
      <li><a href="http://news.railstutorial.org/">News</a></li>
    </ul>
  </nav>
</footer>
</html>

app/views/mytasks/finish.html.erb
<h1>Mytasks#finish</h1>
<p>Find me in app/views/mytasks/finish.html.erb</p>

app/views/mytasks/info.html.erb
<h1>Mytasks#info</h1>
<p>Find me in app/views/mytasks/info.html.erb</p>

app/views/mytasks/show.html.erb
<h1>My Tasks</h1>
<p>Here are tasks you have accepted. Don't keep the patricians waiting, get on them.</p>

<p>...insert table...</p>

app/views/mytasks/unaccept.html.erb
<h1>Mytasks#unaccept</h1>
<p>Find me in app/views/mytasks/unaccept.html.erb</p>

app/views/opentasks/accept.html.erb
<h1>Opentasks#accept</h1>
<p>Find me in app/views/opentasks/accept.html.erb</p>

app/views/opentasks/create.html.erb
<h1>Opentasks#create</h1>
<p>Find me in app/views/opentasks/create.html.erb</p>

app/views/opentasks/delete.html.erb
<h1>Opentasks#delete</h1>
<p>Find me in app/views/opentasks/delete.html.erb</p>

app/views/opentasks/new.html.erb
<h1>Opentasks#new</h1>
<p>Find me in app/views/opentasks/new.html.erb</p>

app/views/opentasks/show.html.erb
<h1>Open Tasks</h1>
<p>View available tasks and select those you wish to complete.</p>

<p>...insert table...</p>

app/views/welcome/index.html.erb
<div class="center jumbotron">
<h1>SquidMinion: The Superior Task Publishing Service</h1>

<h2>Hello peeps</h2>

<h1>Welcome - This is the Login Page </h1>
<p>Find me in app/views/welcome/index.html.erb</p>

  <% if poster_signed_in? %>
  <li>
  hi there
  <%= link_to('Logout', destroy_poster_session_path, :method => :delete) %>
  </li>
	<% else %>
  <li>
  hello there
  <%= link_to('Login', new_poster_session_path)  %>
  </li>
</div>

	<% end %>